apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: igait-secrets
  namespace: igait
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: igait-secrets
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /igait/prod/env/
      rewrite:
        - regexp:
            source: "^/igait/prod/env/(.+)$"
            target: "$1"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-key
  namespace: igait
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: gcp-key
    creationPolicy: Owner
  data:
    - secretKey: gcp-key.json
      remoteRef:
        key: /igait/prod/gcp-key/key.json
