{{- if .Values.emulators.ses.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "igait.fullname" . }}-ses-mock
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "igait.labels" . | nindent 4 }}
    app.kubernetes.io/component: ses-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "igait.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ses-mock
  template:
    metadata:
      labels:
        {{- include "igait.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ses-mock
    spec:
      containers:
        - name: ses-mock
          image: {{ .Values.emulators.ses.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.emulators.ses.port }}
              name: http
          resources:
            {{- toYaml .Values.emulators.ses.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "igait.fullname" . }}-ses-mock
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "igait.labels" . | nindent 4 }}
    app.kubernetes.io/component: ses-mock
spec:
  type: ClusterIP
  selector:
    {{- include "igait.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ses-mock
  ports:
    - name: http
      port: {{ .Values.emulators.ses.port }}
      targetPort: {{ .Values.emulators.ses.port }}
{{- end }}
