apiVersion: v1
kind: Service
metadata:
  name: firebase-emulator
  labels:
    app: firebase-emulator
spec:
  type: ClusterIP
  selector:
    app: firebase-emulator
  ports:
    - name: rtdb
      port: 9000
      targetPort: 9000
    - name: auth
      port: 9099
      targetPort: 9099
    - name: ui
      port: 4000
      targetPort: 4000
