apiVersion: v1
kind: Service
metadata:
  name: ses-mock
  labels:
    app: ses-mock
spec:
  type: ClusterIP
  selector:
    app: ses-mock
  ports:
    - name: http
      port: 8005
      targetPort: 8005
